sehirler=list(("Ankara","Ankara","Istanbul"))
print(sehirler)
print(len(sehirler))
#print(sehirler.count("Ankara"))
print("Ankara sayisi= "+str(sehirler.count("Ankara")))
sehirler.insert(0,"Aydin")
print(sehirler)
sehirler.reverse()
print(sehirler)
sehirler.extend()